Fix get credentials with password with length one (#62)
AdysTech/CredentialManager pull request #63
Opened 2021-08-18 13:24 UTC by aschoelzhorn

2021-08-18 13:25 UTC, aschoelzhorn commented
I fixed also a typo in the tests

2021-08-29 03:05 UTC, mvadu requested changes
Can you also update the minor version so that I can push to nuget? (https://github.com/aschoelzhorn/CredentialManager/blob/2ca85ebf762d242983de559fb673258c5a3d4b51/src/AdysTech.CredentialManager/AdysTech.CredentialManager.csproj#L11) should be updated.

2021-08-29 03:06 UTC, mvadu commented
Thank you for the contribution @aschoelzhorn . I was out for few days and catching up just now. I just left a comment requesting a change. If you could update minor version I will merge this.

2021-08-31 03:47 UTC, mvadu approved these changes

2021-08-31 03:48 UTC, merged